// Generated by CoffeeScript 2.0.0-beta4
import * as TYPES from './types';

import * as message from './messageAct';

import * as Route from '../routes';

import * as net from '../network';

import {
  output_error
} from './mainAct';

export var updateList = (list) => {
    return (dispatch) => {
    return dispatch({
      type: TYPES.UPDATE_CONTACT_LIST,
      list: list
    });
  };
};

export var openChat = (contact) => {
    return (dispatch) => {
    dispatch(message.convert(contact.pivot.session_id));
    Route.Push(Route.CHATROOM);
    return dispatch({
      type: TYPES.OPEN_CHAT
    });
  };
};

export var getContactQRCode = () => {
    return (dispatch) => {
        return new Promise((resolve, reject) => {
            return net.contact.get_add_qrtoken().then((data) => {
                dispatch({
                    type: TYPES.GET_QRCODE,
                    qr_token: data
                });
                return resolve(data);
            }, (data) => {
                dispatch(output_error(data));
                return reject(data);
      });
    });
  };
};

export var addContactByQRCode = (token) => {
    return (dispatch) => {
        return net.contact.add_by_qrtoken(token).then(((profile) => {
            console.log('Success to add friend');
      return dispatch({
        type: TYPES.ADD_CONTACT_BY_QRCODE,
        profile: profile
      });
        }), (data) => {
            switch (data.error_code) {
        case 1:
          return dispatch(output_error('二维码无效'));
        case 2:
          return dispatch(output_error('二维码无效'));
        case 3:
          return dispatch(output_error('不可以添加自己'));
        case 4:
          return dispatch(output_error('已经在好友列表里'));
        case 5:
          return dispatch(output_error('用户不存在'));
      }
    });
  };
};

//# sourceMappingURL=contactAct.js.map

// ---
// generated by js2coffee 2.2.0

//# sourceMappingURL=contactAct.js.map
