import * as TYPES from './types'
import * as message from './messageAct'
import * as Route from '../routes'
import * as net from '../network'
import {
  output_error
} from './mainAct'

export updateList = (list) =>
  (dispatch) =>
    dispatch
      type: TYPES.UPDATE_CONTACT_LIST
      list: list

export openChat = (contact) =>
  (dispatch) =>
    dispatch message.convert(contact.pivot.session_id)
    Route.Push Route.CHATROOM
    dispatch type: TYPES.OPEN_CHAT

export getContactQRCode = =>
  (dispatch) =>
    new Promise((resolve, reject) =>
      net.contact.get_add_qrtoken()
        .then(
        (data)=>
          dispatch
            type: TYPES.GET_QRCODE
            qr_token: data
          resolve data
        (data)=>
          dispatch output_error data
          reject data
      )
    )

export addContactByQRCode = (token) =>
  (dispatch) =>
    net.contact.add_by_qrtoken(token).then ((profile) =>
      console.log 'Success to add friend'
      dispatch
        type: TYPES.ADD_CONTACT_BY_QRCODE
        profile: profile
    ), (data) =>
      switch data.error_code
        when 1 then dispatch output_error '二维码无效'
        when 2 then dispatch output_error '二维码无效'
        when 3 then dispatch output_error '不可以添加自己'
        when 4 then dispatch output_error '已经在好友列表里'
        when 5 then dispatch output_error '用户不存在'

## sourceMappingURL=contactAct.js.map

# ---
# generated by js2coffee 2.2.0
