// Generated by CoffeeScript 2.0.0-beta4
import * as Route from '../routes';

export var openImage = (uri) => {
  return (dispatch) => {
    Route.Push(Route.IMAGE_PLAYER, {
      uri: uri
    });
    return dispatch({
      type: TYPES.PLAY_IMAGE
    });
  };
};

//# sourceMappingURL=imageAct.js.map
