// Generated by CoffeeScript 2.0.0-beta4
//#This file gives an example for creating a page
var ImagePlayer, selectActions, selectProps;

import {
  Page
} from '../Component';

import React from 'react';

import {
  bindActionCreators
} from 'redux';

import View from 'react-native';

import {
  Image
} from '../Component';

import * as style from '../style';

ImagePlayer = (function() {
  var render;

  class ImagePlayer extends React.Component {};

  render = () => {
    return <Image height={style.device.width} width={style.device.width} {...this.props}> </Image>;
  };

  return ImagePlayer;

})();

selectProps = (state) => {
  return {};
};

selectActions = (dispatch) => {
  return bindActionCreators({}, dispatch);
};

export default Page.Pure(selectProps, selectActions, myPage);

//# sourceMappingURL=imagePlayer.js.map
