export * as color from './color'
export * as fontSize from './fontSize'
export * as device from './device'
export * as avatar from './avatar'
export * as chatroom from './chatroom'
export * as page from './page'
export {StyleSheet} from 'react-native'
