// Generated by CoffeeScript 2.0.0-beta4
var Image;

import React from 'react';

import RN from 'react-native';

Image = class Image extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        console.log(this.props.uri);
        return <RN.Image source={{
            uri: this.props.uri
        }} mutable={this.props.mutable} style={{
            height: this.props.height,
            width: this.props.width
        }}/>;
    }

};

export default Image;

//# sourceMappingURL=Image.js.map
