// Generated by CoffeeScript 2.0.0-beta4
import * as codes from '../codes';

import csrf from './csrf';

import fetch_factory from './fetch_factory';

export var http_login = function(username, token) {
  return new Promise(function(reslove, reject) {
    return fetch_factory('/auth/token_login', 'POST', {
      username: username,
      token: token
    }).then(function(data) {
      if (data['status'] === 1) {
        return reslove();
      } else {
        return reject({
          error: codes.error.verify_id_failed,
          message: "身份验证失败"
        });
      }
    }, function(error) {
      return reject(error);
    });
  });
};

export var login = function(username, password) {
  return new Promise(function(reslove, reject) {
    return fetch_factory('/auth/login', 'POST', {
      username: username,
      password: password
    }).then(function(data) {
      if (data['status'] === 1) {
        return reslove(data);
      } else {
        return reject(data);
      }
    }, function(error) {
      return reject(error);
    });
  });
};

//# sourceMappingURL=auth.js.map
