// Generated by CoffeeScript 2.0.0-beta4
import request from './fetch_factory';

export var getlist = () => {
  return new Promise((resolve, reject) => {
    return request('/contact').then((data) => {
      return resolve(data);
    }, (err) => {
      return reject(err);
    });
  });
};

export var get_add_qrtoken = () => {
  return new Promise((resolve, reject) => {
    return request('/contact/create_add_qr').then((data) => {
      if (data['status'] === 1) {
        return resolve(data.qr_token);
      } else {
        return reject(data);
      }
    }, (data) => {
      return reject(data);
    });
  });
};

export var add_by_qrtoken = (token) => {
  return new Promise((resolve, reject) => {
    return request('/contact/add_by_qr', 'POST', {
      token: token
    }).then((data) => {
      if (data.status === 1) {
        return resolve(data);
      } else {
        return reject(data);
      }
    }, (data) => {
      return reject(data);
    });
  });
};

export var test = (token) => {};

//# sourceMappingURL=contacts.js.map
